"""title field in events model

Revision ID: 012d33cdad4d
Revises: ae2faf7dacd3
Create Date: 2021-12-23 21:37:01.050541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012d33cdad4d'
down_revision = 'ae2faf7dacd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_update events_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update events_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
