"""update blog table

Revision ID: 11f91df9c7c6
Revises: 3d4eeb4d5e3b
Create Date: 2021-12-23 21:13:51.002350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f91df9c7c6'
down_revision = '3d4eeb4d5e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_image', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('link', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update blog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update blog_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_update blog_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update blog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update blog_title'))
        batch_op.drop_index(batch_op.f('ix_update blog_timestamp'))

    op.drop_table('update blog')
    # ### end Alembic commands ###
