"""data science student stories

Revision ID: 20e4d5ae4934
Revises: 7708ec5e94c5
Create Date: 2021-12-25 11:52:28.170893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e4d5ae4934'
down_revision = '7708ec5e94c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data science student stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('student_image', sa.String(length=300), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data science student stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data science student stories_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_data science student stories_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data science student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data science student stories_username'))
        batch_op.drop_index(batch_op.f('ix_data science student stories_timestamp'))

    op.drop_table('data science student stories')
    # ### end Alembic commands ###
