"""student stories table

Revision ID: 33087384e06e
Revises: 012d33cdad4d
Create Date: 2021-12-23 21:40:21.810271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33087384e06e'
down_revision = '012d33cdad4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update student stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_image', sa.String(length=140), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update student stories_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update student stories_timestamp'))

    op.drop_table('update student stories')
    # ### end Alembic commands ###
