"""allowed status field in update events model

Revision ID: 370f980a9cfa
Revises: c52f367b93e6
Create Date: 2021-12-24 00:09:43.556506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370f980a9cfa'
down_revision = 'c52f367b93e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.drop_column('allowed_status')

    # ### end Alembic commands ###
