"""flask student stories table

Revision ID: 428e3d55c40b
Revises: d4307c2cc901
Create Date: 2021-12-24 05:54:09.736610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428e3d55c40b'
down_revision = 'd4307c2cc901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask student stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('student_image', sa.String(length=140), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flask student stories_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_flask student stories_username'), ['username'], unique=False)

    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.drop_index('ix_update student stories_timestamp')
        batch_op.drop_index('ix_update student stories_username')

    op.drop_table('update student stories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update student stories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_image', sa.VARCHAR(length=140), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('allowed_status', sa.BOOLEAN(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.create_index('ix_update student stories_username', ['username'], unique=False)
        batch_op.create_index('ix_update student stories_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flask student stories_username'))
        batch_op.drop_index(batch_op.f('ix_flask student stories_timestamp'))

    op.drop_table('flask student stories')
    # ### end Alembic commands ###
