"""Index the blog post

Revision ID: 4d99c5adae8a
Revises: e367846ac555
Create Date: 2020-06-06 02:40:20.438780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d99c5adae8a'
down_revision = 'e367846ac555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_blog_post'), 'user', ['blog_post'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_blog_post'), table_name='user')
    # ### end Alembic commands ###
