"""events table

Revision ID: bac8179ceaf3
Revises: 11f91df9c7c6
Create Date: 2021-12-23 21:25:14.792701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac8179ceaf3'
down_revision = '11f91df9c7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_image', sa.String(length=140), nullable=True),
    sa.Column('event_date', sa.String(length=140), nullable=True),
    sa.Column('event_time', sa.String(length=140), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=140), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update events_timestamp'))

    op.drop_table('update events')
    # ### end Alembic commands ###
