"""username field in student stories table

Revision ID: d4307c2cc901
Revises: 5cedcacbc59c
Create Date: 2021-12-24 04:36:21.524494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4307c2cc901'
down_revision = '5cedcacbc59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_update student stories_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update student stories_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
