"""Create a timestamp

Revision ID: e367846ac555
Revises: aee54dee9727
Create Date: 2020-06-06 02:24:19.374135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e367846ac555'
down_revision = 'aee54dee9727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog_post', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blog_post')
    # ### end Alembic commands ###
